#!/usr/bin/env bash
#
# run-gnmi-peer.sh — deploy the grace-server gNMI peer to receive dial-out
#                    telemetry from a Tarana device (radio/BN) on the LAN.
#
# It generates an endpoint.lua and starts the gnmi_peer container DETACHED,
# publishing the local gNMI port so the device can dial in and push updates.
#
# IP rules (the part everyone gets wrong):
#   * local.endpoint ALWAYS binds 0.0.0.0 (all interfaces inside the container).
#     Never put a host/specific IP here — a non-local bind address makes the
#     listener silently fail to start.
#   * The device reaches the peer at the DOCKER HOST's real LAN IP through the
#     published port (-p). Configure that host IP on the DEVICE side.
#   * REMOTE_IP below is the DEVICE's LAN IP; it is only used when the peer
#     itself dials out (gnmi get/set/subscribe). For pure device-push it can be
#     left at the device address for completeness.
#
# Usage:
#   REMOTE_IP=169.254.100.1 ./run-gnmi-peer.sh
#   REMOTE_IP=192.168.100.2 REMOTE_PORT=55555 LOCAL_PORT=58989 ./run-gnmi-peer.sh
#   IMAGE=gnmiserver:dev TLS=true ./run-gnmi-peer.sh      # mTLS via baked certs
#
# Env (all optional except REMOTE_IP):
#   IMAGE        container image                 (default: gnmiserver:dev)
#   CONTAINER    container name                  (default: gnmi_peer)
#   LOCAL_PORT   port the peer listens on        (default: 58989)
#   REMOTE_IP    the Tarana device's LAN IP      (REQUIRED)
#   REMOTE_PORT  the device's gNMI/dial port     (default: 55555)
#   CONFIG       generated endpoint.lua path     (default: ./endpoint.lua)
#   TLS          true|false                      (default: false)
#   FOLLOW       tail logs after start (1|0)     (default: 1)
set -euo pipefail

IMAGE="${IMAGE:-gnmiserver:dev}"
CONTAINER="${CONTAINER:-gnmi_peer}"
LOCAL_PORT="${LOCAL_PORT:-58989}"
REMOTE_IP="${REMOTE_IP:-}"
REMOTE_PORT="${REMOTE_PORT:-55555}"
CONFIG="${CONFIG:-$(pwd)/endpoint.lua}"
TLS="${TLS:-false}"
FOLLOW="${FOLLOW:-1}"

die() { echo "run-gnmi-peer.sh: $*" >&2; exit 1; }

[ -n "$REMOTE_IP" ] || die "set REMOTE_IP=<device LAN ip>  (see --help / header)"
case "$TLS" in true|false) ;; *) die "TLS must be true or false" ;; esac
command -v docker >/dev/null 2>&1 || die "docker not found on this host"

# TLS paths point at certs baked into the image at /app/certs/ (see Dockerfile).
if [ "$TLS" = true ]; then
  CERT="/app/certs/server.pem"; KEY="/app/certs/server.key"; CA="/app/certs/ca.pem"
else
  CERT=""; KEY=""; CA=""
fi

# 1. Generate endpoint.lua — local ALWAYS 0.0.0.0.
cat > "$CONFIG" <<EOF
-- generated by run-gnmi-peer.sh — do not hand-edit; re-run the script instead.
return {
  ["local"]  = { endpoint = { ip = "0.0.0.0", port = ${LOCAL_PORT} } },
  ["remote"] = { endpoint = { ip = "${REMOTE_IP}", port = ${REMOTE_PORT} } },
  tls = { enabled = ${TLS}, cert = "${CERT}", key = "${KEY}", ca = "${CA}" },
}
EOF
echo "[run-gnmi-peer] wrote config: $CONFIG"
sed 's/^/    /' "$CONFIG"

# 2. (Re)start the container detached so stdin-EOF can never kill it.
docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
echo "[run-gnmi-peer] starting '$CONTAINER' from '$IMAGE' …"
docker run -d --name "$CONTAINER" \
  -p "${LOCAL_PORT}:${LOCAL_PORT}" \
  -v "${CONFIG}:/app/command/endpoint.lua:ro" \
  "$IMAGE" /app/gnmi_peer --config=/app/command/endpoint.lua --headless=true >/dev/null

# 3. Show what got published and where the device should aim.
docker ps --filter "name=${CONTAINER}" \
  --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
host_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
echo "[run-gnmi-peer] device should dial:  ${host_ip:-<this-host-LAN-ip>}:${LOCAL_PORT}"
echo "[run-gnmi-peer] watch for '[IsAlive] ... -> OK' then '[Set]' / '[remote]' lines."

if [ "$FOLLOW" = 1 ]; then
  echo "[run-gnmi-peer] tailing logs (Ctrl-C to stop; container keeps running) …"
  exec docker logs -f "$CONTAINER"
fi
